webserver:
  build: .
  ports:
    - "18888:8080"
  links:
    - database:database
  volumes:
    - ./config/:/usr/local/tomcat/conf/Catalina/localhost/

database:
  image: postgres:9.5.3
  expose:
    - 5432
  environment:
    POSTGRES_PASSWORD: labkeydbpass
