webserver:
  build: .
  ports:
    - "18888:8080"
  links:
    - database:database
  volumes:
    - ./config/:/usr/local/tomcat/conf/Catalina/localhost/
    - ./files/:/usr/local/labkey/files/

database:
  image: postgres:9.6.3-alpine
  expose:
    - 5432
  environment:
    POSTGRES_PASSWORD: labkeydbpass
  volumes:
    - ./data/:/var/lib/postgresql/data/
